FROM jenkins/jenkins:lts

USER root

# Install docker CLI from Debian repo safely
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins